fixing video skeleton loader
atlp-rwanda/elite-bn-frontend pull request #14
Opened 2021-02-10 14:39 UTC by ShemaM

**What does this PR do?**
> - Modifying some changes on landing page

**Description of Task to be completed**
> - fixing video skeleton loader
> - making footer background white
> - making testimonials bg-gray-200
> - making footer bg-white
> - making the log a link

**How should this be manually tested?**
> - git clone to `https://github.com/atlp-rwanda/elite-bn-frontend.git`
> - checkout to `ft-landing-page`
> - `npm install` to install node_modules
> - `npm start` to start server
> - open http://localhost:8080/ to view it in the browser.

**What are the relevant Trello story?**
> - https://trello.com/c/HScI66re

2021-02-10 16:10 UTC, pextech requested changes

2021-02-10 16:10 UTC, pextech commented on src/components/LandingPage/TestmonialCard.js
> +    <div className="shadow-lg bg-gray-200  flex flex-col justify-around items-center mb-10 md:mb-0">
make this bg-white, this makes it more perfect

2021-02-10 16:13 UTC, pextech approved these changes

2021-02-10 16:20 UTC, iradukundairenee approved these changes

2021-02-12 09:53 UTC, Patricknshimiyimana approved these changes

2021-02-12 09:57 UTC, merged