bg-updateProfile-errorFix
atlp-rwanda/elite-bn-frontend pull request #26
Opened 2021-03-11 17:54 UTC by bertinNDAYISHIMIYE

###What does this PR do?

>Add appropriate validations
>Add responsiveness 
>Fix image issue

###Relavant trello card
> https://trello.com/c/md049IYG

2021-03-14 19:09 UTC, leny62 requested changes
Great Job! But kindly make some adjustment on responsiveness for smaller screen sizes.

2021-03-14 19:09 UTC, leny62 requested changes
Great Job! But kindly make some adjustment on responsiveness for smaller screen sizes.

2021-03-30 13:41 UTC, leny62 approved these changes

2021-03-30 15:15 UTC, ShemaM approved these changes

2021-03-30 15:16 UTC, NIRoberto approved these changes

2021-03-30 19:37 UTC, mukunzidd approved these changes

2021-03-30 20:25 UTC, merged