Ft reset password
atlp-rwanda/elite-bn-frontend pull request #9
Opened 2021-02-04 10:31 UTC by pextech

What does this PR do?

  changes user password

Description of Task completed

     checks user by email
     grabs user token
     user changes password

How should this be manually tested?

git clone to https://github.com/atlp-rwanda/elite-bn-frontend.git
checkout to ft-reset-password
npm install to install node_modules
npm start to start the server
open http://localhost:8080/reset-password  to view it in the browser.

What is the relevant Trello story?

https://trello.com/c/7bHvy7jz

<img width="1440" alt="Screen Shot 2021-02-04 at 12 30 48" src="https://user-images.githubusercontent.com/57200088/106880279-d9590a80-66e4-11eb-8d04-6e511ab8c547.png">

2021-02-17 05:07 UTC, cniyindagiriye requested changes

2021-02-17 05:07 UTC, cniyindagiriye commented on coverage/lcov-report/sorter.js
> +        currentSort = {
add this to .gitignore

2021-02-17 05:07 UTC, cniyindagiriye commented on src/ExampleFile.test.js
> +// THIS IS AN EXAMPLE FILE TO TESTING WITH JEST & ENZYME
I assume this file was removed

2021-02-23 14:52 UTC, iradukundairenee approved these changes

2021-02-25 20:09 UTC, cniyindagiriye approved these changes

2021-02-26 08:07 UTC, NIRoberto approved these changes

2021-02-26 10:55 UTC, merged